[phases.setup]
nixPkgs = [
    'php83',
    'php83Extensions.pdo_mysql',
    'php83Extensions.gd',
    'php83Extensions.zip',
    'php83Extensions.intl',
    'php83Extensions.bcmath',
    'php83Extensions.mbstring',
    'php83Extensions.curl',
    'php83Extensions.xml',
    'php83Extensions.soap',
    'php83Packages.composer',
    'nodejs_20'
]

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan storage:link || true'
]

[start]
cmd = 'php artisan migrate --seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
